apiVersion: v2
name: loyalty-hub
description: Loyalty Hub vendor neutral - umbrella chart per tutti i servizi (RP-03)
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords: [loyalty, iren, kafka, eks]
