version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      spring:
        patterns:
          - "*spring*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
