apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loyalty-hub
  labels:
    {{- include "lh.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          {{- range $name, $svc := .Values.services }}
          {{- if $svc.expose }}
          - path: {{ $svc.expose.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port: { number: {{ $svc.port }} }
          {{- end }}
          {{- end }}
